name: 3D MOT
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: Run 3D MOT
        run: |
            eval "$(pyenv init -)"
            pyenv activate py37
            ./commands/20_run_kitti.sh
      - name: Upload To Drive
        run: |
            eval "$(pyenv init -)"
            pyenv activate py37
            ./commands/10_upload_source.sh